name: SF Grid — scrape + publish

on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch: {}      # allow manual run

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas jupyter nbconvert
          # add any extra libs your scraper needs (playwright, requests, etc.)
          # pip install playwright
          # python -m playwright install --with-deps chromium

      - name: Run scraper notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace sf_grid_scrape.ipynb

      - name: Build dashboard data
        run: |
          set -euo pipefail
          mkdir -p docs/data
          python - <<'PY'
          import glob
          import pandas as pd

          files = sorted(glob.glob("sfcompute_grid/*.csv"))
          if not files:
              raise SystemExit("No CSV files found in sfcompute_grid/")

          dfs = [pd.read_csv(f) for f in files]
          hist = pd.concat(dfs, ignore_index=True).drop_duplicates()

          hist.to_csv("docs/data/sfcompute_history.csv", index=False)
          pd.read_csv(files[-1]).to_csv("docs/data/sfcompute_latest.csv", index=False)
          print("Wrote docs/data/sfcompute_latest.csv and docs/data/sfcompute_history.csv")
          PY

      - name: Commit dashboard data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add docs/data/*.csv
          git commit -m "Update dashboard data" || echo "No changes"
          git push


